### ISSUE TITLE
There's a small problem in button text overflow "UI" for different screen sizes

### ISSUE THREAD

**Issue by Shashankss1205** [vedantkingh/Located-Voice-CMS#1]
![Screenshot (210)](https://github.com/vedantkingh/Located-Voice-CMS/assets/123410790/f5903544-9d36-4449-a690-36f223ba531d)

**Comment by vedantkingh** [comment]
Unlike other organizations, LG doesn’t have open issues on existing projects for you to create a PR.
LG is a project/task based organization and not an issue based organization.
